### ISSUE TITLE
Add high level description of docs to readme  

### ISSUE THREAD

**Issue by dlebauer** [WSWUP/agweather-qaqc#18]
I’m conducting review for JOSS and will add comments as issues as I go. https://github.com/openjournals/joss-reviews/issues/6368

README should contain a high level overview of the documentation. See https://joss.readthedocs.io/en/latest/review_criteria.html for details

**Comment by cwdunkerly** [comment]
Sorry I've let this one sit so long, I believe the new version of the readme is sufficient, however if you disagree, please reopen the issue.
