### ISSUE TITLE
Corrections in Paper Text

### ISSUE THREAD

**Issue by dostuffthatmatters** [WSWUP/agweather-qaqc#19]
_This issue is related to the review process for JOSS: https://github.com/openjournals/joss-reviews/issues/6368_

Below, you can find some things in the paper that could be corrected. Some of them are rather stylistic:

- [x] Higher resolution image files for Figures 1 and 2; maybe as SVG/EPS?
- [x] Lines 99-100: _"While ease-of-use for a non-technical user was one of the principal goals, the software workflow can be automated with the inclusion of libraries such as PyAutoGUI."_ Automated as in checking for trends/anomalies visually in an automated way?
- [x] Lines 102-109, 116-119, and 125-128 are a repetition of lines 56-98. You could introduce the bullet point list as "In the already described process, the package also performs the following steps: ..." instead of an "all features" list. Since 80-81 does not entirely cover 125-128, you could expand the sentence in 80-81.
- [x] Figure 2: I would prefer having some plot titles (more descriptive than "A", "B", and "C").
- [x] I would move the sections "State of the Field" and "Research enabled by agweather-qaqc" after the "Statement of Need".
- [x] The paper would benefit from a grammar check. I didn't find many, but there are some grammatical errors.

_ADDITION:_ From the repository, it is obvious, that you are the main developer and maintainer of the package. Could you dedicate a small section in the paper to mentioning the roles of the co-authors of the paper?

- [x] clarify the roles of the different authors

**Comment by cwdunkerly** [comment]
Responding to individual points:

1: Done, if you'd like them to be even higher resolution please let me know.
3: I went over the duplicate text you mentioned and identified some more myself, I have trimmed it down appropriately.
4: I changed this plot to have full titles and then referenced the different components by their relative positions.
6: Thank you for the reminder on grammar, I did find a few and fixed them.
7: I added the section you requested. I personally feel this info might be better documented in the repo as opposed to the paper proper, but if you feel differently I understand.

**Comment by dostuffthatmatters** [comment]
@cwdunkerly Thank you for implementing the changes!

Regarding 7: You can also move it to the documentation if you like that better. Having it in the paper is more permanent though. I see that in more and more publication but it is indeed not a standardised thing yet. (ttps://www.elsevier.com/researcher/author/policies-and-guidelines/credit-author-statement)

**Comment by dostuffthatmatters** [comment]
@cwdunkerly 

I opened one more PR (#29) to add more metadata (dois, etc.) to the bibliography.

**Comment by dostuffthatmatters** [comment]
Great! I have no more comments.

**Comment by dostuffthatmatters** [comment]
> @dostuffthatmatters Not going to reopen this but one of the things I am finishing today is changing the author credit to use the terms in the link you shared. Thank you for providing that link.

Oh, sorry for closing it too quickly ^^

**Comment by cwdunkerly** [comment]
No need to apologize, the fault is mine for leaving this open.
